---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: static/content/hireus.json
  label: Hire Us
- type: heading
  label: Seciones
- type: document
  path: static/content/services.json
  label: Services
- type: document
  path: static/content/work.json
  label: Our Work
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
