---
label: General Settings
hide_body: true
fields:
- name: phone
  type: text
  config:
    required: false
  label: Phone
  default: 773-584-1872
- name: promotion
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Promotion
