---
label: Services
hide_body: false
fields:
- name: heading
  type: text
  config:
    required: false
  label: Heading
- name: listing
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Listing
